# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site 基本设置
# title
# 网站标题
title: 小狐窝

# subtitle
# 网站副标题
subtitle: 用梦想点亮世界

# description
# 网站描述
# description 主要用于SEO，
# 告诉搜索引擎一个关于您站点的简单描述，
# 通常建议在其中包含您网站的关键词。
description: 用心记录生活的每一刻

# keywords
# 网站的关键词。支持多个关键词。
keywords: 梦想  blog 博客

# author
# 您的名字
# author 参数用于主题显示文章的作者。
author: lin xiaohu

# language
# 网站使用的语言。对于简体中文用户来说，使用不同的主题可能需要设置成不同的值，
# 请参考你的主题的文档自行设置，常见的有 zh-Hans和 zh-CN。
language: zh-CN

# timezone
# 网站时区。Hexo 默认使用您电脑的时区。
# 请参考 时区列表 进行设置，如 America/New_York, Japan, 和 UTC 。
# 一般的，对于中国大陆地区可以使用 Asia/Shanghai。
timezone: Asia/Shanghai








# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
# url
# 网址, 必须以 http://
# 或 https:// 开头
url: https://hexo.xiaohu.dedyn.io

# root
# 网站根目录
root: /

# permalink
# 文章的 永久链接 格式
# :year	文章的发表年份（4 位数）
# :month	文章的发表月份（2 位数）
# :i_month	文章的发表月份（不含前导零）
# :day	文章的发表日期 (2 位数)
# :i_day	文章的发表日期（不含前导零）
# :hour	文章发表时的小时 (2 位数)
# :minute	文章发表时的分钟 (2 位数)
# :second	文章发表时的秒钟 (2 位数)
# :title	文件名称 (相对于 “source/_posts/“ 文件夹)
# :name	文件名称
# :post_title	文章标题
# :id	文章 ID (清除缓存时不具有持久性)
# :category	分类。如果文章没有分类，则是 default_category 配置信息。
# :hash	文件名（与 :title 相同）和日期的 SHA1 哈希值（12位16进制数）
permalink: posts/:year/:hash/

# permalink_defaults
# 永久链接中各部分的默认值
permalink_defaults:

pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# Directory
# source_dir
# 资源文件夹，这个文件夹用来存放内容
source_dir: source

# public_dir
# 公共文件夹，这个文件夹用于存放生成的站点文件
public_dir: public

# tag_dir
# 标签文件夹
tag_dir: article/tags

# archive_dir
# 归档文件夹
archive_dir: article/archives

# category_dir
# 分类文件夹
category_dir: article/categories

# code_dir
# Include code 文件夹，source_dir 下的子目录
code_dir: downloads/code

# i18n_dir
# 国际化（i18n）文件夹
i18n_dir: lang

# skip_render
# 跳过指定文件的渲染。匹配到的文件将会被不做改动地复制到 public 目录中。您可使用 glob 表达式来匹配路径。
skip_render: .assets/**/**/*

# Writing
# new_post_name
# 新文章的文件名称	:title.md
new_post_name: :title.md # File name of new posts

# default_layout
# 预设布局
default_layout: post

# auto_spacing
# 在中文和英文之间加入空格	false
auto_spacing: false

# titlecase
# 把标题转换为
titlecase: false # Transform title into titlecase

# external_link	在新标签中打开链接	true
# external_link.enable	在新标签中打开链接	true
# external_link.field	对整个网站（site）生效或仅对文章（post）生效	site
# external_link.exclude	需要排除的域名。主域名和子域名如 www 需分别配置	[]
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''

# filename_case
# 把文件名称转换为 (1) 小写或 (2) 大写	0
filename_case: 1

# render_drafts
# 显示草稿	false
render_drafts: false

# post_asset_folder
# 启动 Asset 文件夹
post_asset_folder: true

# relative_link
# 把链接改为与根目录的相对位址	false
relative_link: false

# future
# 显示未来的文章	true
future: true

# highlight
# 代码块的设置, 请参考 Highlight.js 进行设置
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# prismjs
# 代码块的设置, 请参考 PrismJS 进行设置
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 8
  order_by: -date

# Category & Tag
#  default_category	默认分类	uncategorized
default_category: uncategorized

#  category_map	分类别名
category_map:

#  tag_map	标签别名
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/

#  date_format	日期格式	YYYY-MM-DD
date_format: YYYY-MM-DD

#  time_format	时间格式	HH:mm:ss
time_format: HH:mm:ss

#  updated_option	当 Front Matter 中没有指定 updated 时 updated 的取值	mtime
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include: ''
exclude: ''
ignore: ''

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''



# hexo-butterfly-categories-card
# see https://akilar.top/posts/a9131002/
categoryBar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: / # 应用页面
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  column: odd # odd：3列 | even：4列
  row: 1 #显示行数，默认两行，超过行数切换为滚动显示
  message:
    - descr: Ubuntu指南
      cover: https://assets.akilar.top/image/cover1.webp
    - descr: 玩转Win10
      cover: https://assets.akilar.top/image/cover2.webp
    - descr: 长篇小说连载
      cover: https://assets.akilar.top/image/cover3.webp
    - descr: 个人日记
      cover: https://assets.akilar.top/image/cover4.webp
    - descr: 诗词歌赋
      cover: https://assets.akilar.top/image/cover5.webp
    - descr: 杂谈教程
      cover: https://assets.akilar.top/image/cover6.webp
  custom_css: https://npm.elemecdn.com/hexo-butterfly-categories-card@1.0.0/lib/categorybar.css


# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: all # 应用页面
  timemode: date #date/updated
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper css依赖
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js #swiper js依赖
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css # 适配主题样式补丁
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiper初始化方法


wowjs:
  enable: true #控制动画开关。true是打开，false是关闭
  priority: 10 #过滤器优先级
  mobile: false #移动端是否启用，默认移动端禁用
  animateitem:
    - class: recent-post-item #必填项，需要添加动画的元素的class
      style: animate__zoomIn #必填项，需要添加的动画
      duration: 2s #选填项，动画持续时间，单位可以是ms也可以是s。例如3s，700ms。
      delay: 1s #选填项，动画开始的延迟时间，单位可以是ms也可以是s。例如3s，700ms。
      offset: 100 #选填项，开始动画的距离（相对浏览器底部）
      iteration: 2 #选填项，动画重复的次数
    - class: card-widget
      style: animate__zoomIn
  animate_css: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/animate.min.css
  wow_js: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/wow.min.js
  wow_init_js: https://npm.elemecdn.com/hexo-butterfly-wowjs/lib/wow_init.js


# hexo-filter-gitcalendar
gitcalendar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: /about/ # 应用页面
  # butterfly挂载容器
  layout: # 挂载容器类型
    type: id
    name: gitZone
    index: 0
  user: Fomalhaut-Blog #git用户名
  apiurl: 'https://api-gitcalender.xiaohu.dedyn.io'    # 这是我的API，最好自己弄一个
  minheight:
    pc: 280px #桌面端最小高度
    mibile: 0px #移动端最小高度
  color: "['#d9e0df', '#c6e0dc', '#a8dcd4', '#9adcd2', '#89ded1', '#77e0d0', '#5fdecb', '#47dcc6', '#39dcc3', '#1fdabe', '#00dab9']" # 目前我在用的
  # "['#e4dfd7', '#f9f4dc', '#f7e8aa', '#f7e8aa', '#f8df72', '#fcd217', '#fcc515', '#f28e16', '#fb8b05', '#d85916', '#f43e06']" #橘黄色调
  # color: "['#ebedf0', '#fdcdec', '#fc9bd9', '#fa6ac5', '#f838b2', '#f5089f', '#c4067e', '#92055e', '#540336', '#48022f', '#30021f']" #浅紫色调
  # color: "['#ebedf0', '#f0fff4', '#dcffe4', '#bef5cb', '#85e89d', '#34d058', '#28a745', '#22863a', '#176f2c', '#165c26', '#144620']" #翠绿色调
  # color: "['#ebedf0', '#f1f8ff', '#dbedff', '#c8e1ff', '#79b8ff', '#2188ff', '#0366d6', '#005cc5', '#044289', '#032f62', '#05264c']" #天青色调
  container: .recent-post-item(style='width:100%;height:auto;padding:10px;') #父元素容器，需要使用pug语法
  gitcalendar_css: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.css
  gitcalendar_js: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.js

# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # 开关
  priority: 5 #过滤器优先权
  issues: false #issues标签依赖注入开关
  link:
    placeholder: /assets/images/lemon.png #link_card标签默认的图标图片
  CDN:
    anima: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/font-awesome-animation.min.css #动画标签anima的依赖
    jquery: https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js #issues标签依赖
    issues: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/issues.js #issues标签依赖
    iconfont: //at.alicdn.com/t/font_2032782_8d5kxvn09md.js #参看https://akilar.top/posts/d2ebecef/
    carousel: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/carousel-touch.js
    tag_plugins_css: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/tag_plugins.css